apiVersion: v1
kind: Service
metadata:
  name: chat-server-service
spec:
  type: NodePort # exposes the port of the cluster to a random port on your host machine
  selector:
    app: chat-server # connects the service directly to pods defined with this label in the deployment
  ports:
    - name: chat
      port: 9999
      targetPort: 8888 # this is the port that the socat proxy listens on inside the container, forwarding to the actual chat server port 9999
      nodePort: 30099 # we are forcing K8s to open port 30099 on your machine for the client connection!
    - name: metrics
      port: 8080
      targetPort: 8080
      nodePort: 30080 # external Prometheus port