# שלב 1: בנייה (זהה לשרת)
FROM maven:3.9-eclipse-temurin-21 AS build
WORKDIR /app
COPY pom.xml .
RUN mvn dependency:go-offline -B
COPY src ./src
RUN mvn package -DskipTests

# שלב 2: הרצה
FROM eclipse-temurin:21-jre
WORKDIR /app
COPY --from=build /app/target/tcp-chat-1.0-SNAPSHOT.jar app.jar

# דגש: כאן אנחנו מריצים ספציפית את ה-Client ולא את ה-Server
CMD ["java", "-cp", "app.jar", "Client"]