name: Java CI with MongoDB

on:
  push:
    branches: [ "main" ]  # הרובוט ירוץ בכל פעם שתעשה Push לענף הראשי
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # המכונה שעליה הכל ירוץ

    # כאן אנחנו מגדירים ל-GitHub להרים MongoDB זמני לצורך הטסטים
    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # מוריד את הקוד שלך למכונה הווירטואלית

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Run Tests with Maven
      run: mvn test  # הפקודה שמריצה את ה-JUnit שכתבנו
      env:
        DB_HOST: localhost  # אומר לשרת שהמונגו נמצא ב-localhost של המכונה הווירטואלית