name: Java CI with MongoDB

on:
  push:
    branches: [ "main" ]  # The workflow will run every time you push to the main branch
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # The runner environment for the job

    # Defining a service container to run MongoDB for the tests
    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Clones your repository onto the virtual machine

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Run Tests with Maven
      run: mvn test  # Command to execute the JUnit tests
      env:
        DB_HOST: localhost  # Tells the application that MongoDB is running on the local host of the runner